name: settings
description: Settings module for Biv Manager (scaffold)
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  core:
    path: ../core
  shared:
    path: ../shared
  auth:
    path: ../auth
  cloud_firestore: ^5.6.8
  equatable: ^2.0.5
  firebase_remote_config: ^5.4.4
  flutter_bloc: ^9.1.1
  get_it: ^8.0.3
  go_router: ^15.1.2
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
