name: shared
description: Shared UI components and utilities for Biv Manager
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  core:
    path: ../core
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  go_router: ^15.1.2
  google_fonts: ^6.1.0
  intl: ^0.20.2
  responsive_framework: ^1.4.0
  shared_preferences: ^2.2.2
  internet_connection_checker: ^3.0.1
  equatable: ^2.0.5

dev_dependencies:
  flutter_lints: ^6.0.0
