name: biv_manager
description: A debt management application.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  cloud_firestore: ^5.6.8
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  firebase_analytics: ^11.4.6
  firebase_auth: ^5.5.4
  firebase_core: ^3.13.1
  firebase_remote_config: ^5.4.4
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  get_it: ^8.0.3
  go_router: ^15.1.2
  google_fonts: ^6.2.0
  internet_connection_checker: ^3.0.1
  intl: any
  logger: ^2.0.2+1
  responsive_framework: ^1.4.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-VariableFont_wdth,wght.ttf
        - asset: assets/fonts/Roboto/Roboto-Italic-VariableFont_wdth,wght.ttf
          style: italic
