name: app
description: Main app package for Biv Manager
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  core:
    path: ../core
  shared:
    path: ../shared
  auth:
    path: ../auth
  customer:
    path: ../customer
  transaction:
    path: ../transaction
  flutter:
    sdk: flutter
  go_router: ^15.1.2
  firebase_core: ^3.13.1
  responsive_framework: ^1.4.0
  cupertino_icons: ^1.0.2
  firebase_remote_config: ^5.4.4
  get_it: ^8.0.3
  shared_preferences: ^2.2.2
  flutter_localizations:
    sdk: flutter
  internet_connection_checker: ^3.0.1
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
