name: auth
description: Authentication module for Biv Manager
version: 1.0.0

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  core:
    path: ../core
  shared:
    path: ../shared
  firebase_auth: ^5.5.4
  firebase_core: ^3.13.1
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  go_router: ^15.1.2
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_lints: ^6.0.0
