name: app
description: Main app package for Biv Manager
version: 1.0.0

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  core:
    path: ../core
  shared:
    path: ../shared
  auth:
    path: ../auth
  customer:
    path: ../customer
  transaction:
    path: ../transaction
  flutter:
    sdk: flutter
  firebase_core: ^3.13.1
  responsive_framework: ^1.4.0
  cupertino_icons: ^1.0.2
  firebase_remote_config: ^5.4.4
  flutter_localizations:
    sdk: flutter
  internet_connection_checker: ^3.0.1

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-VariableFont_wdth,wght.ttf
        - asset: assets/fonts/Roboto/Roboto-Italic-VariableFont_wdth,wght.ttf
          style: italic
