name: customer
description: Customer management module for Biv Manager
version: 1.0.0

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  core:
    path: ../core
  shared:
    path: ../shared
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5
  cloud_firestore: ^5.6.8

dev_dependencies:
  flutter_lints: ^6.0.0
