name: core
description: Core utilities and shared components for Biv Manager
version: 1.0.0

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  equatable: ^2.0.5
  get_it: ^8.0.3

dev_dependencies:
  flutter_lints: ^6.0.0
