name: transaction
description: Transaction management module for Biv Manager
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  core:
    path: ../core
  shared:
    path: ../shared
  customer:
    path: ../customer
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5
  cloud_firestore: ^5.6.8
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_lints: ^6.0.0
